Fix edge models for UC24
snapcore/models pull request #18
Opened 2023-12-05 13:54 UTC by alfonsosanchezbeato

The id was wrong for the core24 snap. Furthermore, change pc-kernel channel to 24/beta as edge channels are not signed with Canonical keys anymore.

2023-12-05 13:55 UTC, alfonsosanchezbeato commented
Fixes issues with https://github.com/snapcore/models/pull/17

2023-12-05 14:17 UTC, sil2100 requested changes
Are the timestamps correct? They seem to go into the future, or am I just seeing things? `"timestamp": "2023-12-08T12:22:51+00:00"` sounds like something that's in 3 days. I thought one can't really sign model assertions that are with future dates?

2023-12-05 14:21 UTC, alfonsosanchezbeato commented
> Are the timestamps correct? They seem to go into the future, or am I just seeing things? `"timestamp": "2023-12-08T12:22:51+00:00"` sounds like something that's in 3 days. I thought one can't really sign model assertions that are with future dates?

Well, it is not like "snap sign" cares too much. I think I edited the assertions and put a wrong date. I can ask to re-sign... or maybe just wait 3 days to get it merged.

2023-12-08 14:55 UTC, sil2100 approved these changes

2023-12-08 14:55 UTC, merged